export const endpoint = `http://localhost:4000`;

export const TICKER_LIST_REQUEST = 'TICKER_LIST_REQUEST'
export const TICKER_LIST_SUCCESS = 'TICKER_LIST_SUCCESS'
export const TICKER_LIST_FAIL = 'TICKER_LIST_FAIL'


export const TICKER_DISPLAY_LIST_LOAD = 'TICKER_DISPLAY_LIST_LOAD'
export const TICKER_DISPLAY_LIST_UPDATE = 'TICKER_DISPLAY_LIST_UPDATE'
export const TICKER_DISPLAY_LIST_FAIL = 'TICKER_DISPLAY_LIST_FAIL'

